### PR TITLE
Dark mode + adaptive design

### PR DESCRIPTION
**Pull request by GustavoPeredo**
Hello Unrud! While video-downloader was down, I thought about maintaining the project, along the way I implememented a dark mode and improved the adaptiveness of the app! I hope you like this merge request, I tried to resolve most conflicts, but I've also been having a weird error when building libhandy (`subprocess.CalledProcessError: Command '['glib-compile-resources', 'src/handy.gresources.xml', '--generate-dependencies', '--sourcedir', 'src']' returned non-zero exit status 127.`), so I can't test if eveything is actually working :(

### CODE REVIEW

**Comment by GustavoPeredo** [comment]
Cool to see that features being implemented! Regarding dark mode, what part did you find gimmicky? I can work on that, if you want to

**Comment by Unrud** [comment]
> Regarding dark mode, what part did you find gimmicky? I can work on that, if you want to

Your implementation is not the problem. It looks quite nice. I just don't think that having a dark mode switch is very useful in this app.

**Comment by GustavoPeredo** [comment]
Hmmm, but is also not a bad feature to have... And then I can remove my version off of flathub because all features would be there! :)

**Comment by GustavoPeredo** [comment]
I can make a 'clean' pull request with only the dark mode feature if you want...

**Pull request closed without merging**
